### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by jackrobson** [kacole2/express-node-mongo-skeleton#6]
Error: Cannot find module 'mongodb/node_modules/bson'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jack/Sites/express-node-mongo-skeleton-master/node_modules/mongoose/lib/drivers/node-mongodb-native/objectid.js:8:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

Fixed by changing Mongoose version to latest (4.8.1)

**Comment by kacole2** [comment]
please submit a PR
