### ISSUE TITLE
Getting error after cloning

### ISSUE THREAD

**Issue by sunilpatra27** [kacole2/express-node-mongo-skeleton#7]
localhost:3000/blobs while doing the getting error 

Not Found
404
Error: Not Found
    at D:\Gitrippo\nodewebapp\routes\blobs.js:97:23
    at D:\Gitrippo\nodewebapp\node_modules\mongoose\lib\model.js:3928:16
    at D:\Gitrippo\nodewebapp\node_modules\kareem\index.js:246:48
    at D:\Gitrippo\nodewebapp\node_modules\kareem\index.js:135:16
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

![screenshot 28](https://user-images.githubusercontent.com/35721340/35768660-9be3aaae-0925-11e8-841c-0e87c28ffc71.png)

**Comment by kacole2** [comment]
@sunilpatra27 unfortunately my work gets in the way and i'm not maintaining this repo any longer. If you figure out a fix please submit a PR.
